on: push 

jobs:
  jobs1:
    runs-on: ubuntu-latest
    
    steps:
    - name: 读取仓库内容
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: 安装环境
      run: sudo apt install -y libglfw3-dev

    - name: 打包构建
      run: |
        cd imgui_version
        mkdir build
        cd build 
        cmake ..
        make -j4

