on: push 

jobs:
  jobs1:
    runs-on: ubuntu-latest
    
    steps:
    - name: 读取仓库内容
      uses: actions/checkout@v4

    - name: 打包构建
      run: |
        cd imgui_version
        cmake ..
        cd build 
        make -j4

